cytogenetic	dict.txt:1
cylinders	dict.txt:1
cyrene	bible.txt:4
cyanide	dict.txt:1
cycles	dict.txt:1
cylinder	dict.txt:1
cygnet	dict.txt:1
cypresses	dict.txt:1
cyclotron	dict.txt:1
cynics	dict.txt:1
cynicism	dict.txt:1
cymbals	dict.txt:1	bible.txt:16
cystic	dict.txt:1
cyan	dict.txt:1
cycloid	dict.txt:1
cyclically	dict.txt:1
cybernetics	dict.txt:1
cyberspace	dict.txt:1
cytosine	dict.txt:1
cynic	dict.txt:1
cynical	dict.txt:1
cyrenian	bible.txt:2
cyphers	dict.txt:1
cygnets	dict.txt:1
cysts	dict.txt:1
cycleways	dict.txt:1
cyanogen	dict.txt:1
cylindrically	dict.txt:1
cybernetic	dict.txt:1
cysteine	dict.txt:1
cypher	dict.txt:1
cytotoxic	dict.txt:1
cyclists	dict.txt:1
cycleway	dict.txt:1
cyclic	dict.txt:1
cyborg	dict.txt:1
cyclones	dict.txt:1
cyclone	dict.txt:1
cytoplasmic	dict.txt:1
cyrenians	bible.txt:1
cytological	dict.txt:1
cytoplasm	dict.txt:1
cynically	dict.txt:1
cycle	dict.txt:1
cymbal	dict.txt:1	bible.txt:1
cycled	dict.txt:1
cycling	dict.txt:1
cypress	dict.txt:1	bible.txt:1
cyst	dict.txt:1
cystitis	dict.txt:1
cyrus	bible.txt:23
cyclical	dict.txt:1
cyberpunk	dict.txt:1
cytochrome	dict.txt:1
cytology	dict.txt:1
cyprus	bible.txt:8
cyclist	dict.txt:1
cyclotrons	dict.txt:1
cylindrical	dict.txt:1
cyrenius	bible.txt:1
