ion	dict.txt:1
iota	dict.txt:1
ionizing	dict.txt:1
ionisation	dict.txt:1
ionic	dict.txt:1
ions	dict.txt:1
ionised	dict.txt:1
ionization	dict.txt:1
ionosphere	dict.txt:1
ionise	dict.txt:1
iodide	dict.txt:1
ionospheric	dict.txt:1
ionized	dict.txt:1
ionising	dict.txt:1
ionize	dict.txt:1
iodine	dict.txt:1
