lysine	dict.txt:1
lye	dict.txt:1
lymphocyte	dict.txt:1
lymphomas	dict.txt:1
lychee	dict.txt:1
lyric	dict.txt:1
lycaonia	bible.txt:2
lynchpin	dict.txt:1
lychees	dict.txt:1
lymphoid	dict.txt:1
lydia	bible.txt:3
lying	dict.txt:1	bible.txt:57
lycia	bible.txt:1
lymphoma	dict.txt:1
lystra	bible.txt:6
lysanias	bible.txt:1
lydians	bible.txt:1
lymphocytic	dict.txt:1
lyricists	dict.txt:1
lymphatic	dict.txt:1
lynched	dict.txt:1
lyrical	dict.txt:1
lyrically	dict.txt:1
lymphocytes	dict.txt:1
lynch	dict.txt:1
lynching	dict.txt:1
lysias	bible.txt:3
lynx	dict.txt:1
lyre	dict.txt:1
lydda	bible.txt:3
lynxes	dict.txt:1
lyricism	dict.txt:1
lyricist	dict.txt:1
lyres	dict.txt:1
lyrics	dict.txt:1
lynches	dict.txt:1
lymph	dict.txt:1
